// <auto-generated />
using System;
using Logbook.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Logbook.DataLayer.Migrations
{
    [DbContext(typeof(LogbookContext))]
    [Migration("20200422202938_Updated Aircraft type according to ICAO aircraft database")]
    partial class UpdatedAircrafttypeaccordingtoICAOaircraftdatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Logbook.DataLayer.Aircraft", b =>
                {
                    b.Property<int>("AircraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Registration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeAircraftTypeId")
                        .HasColumnType("int");

                    b.HasKey("AircraftId");

                    b.HasIndex("TypeAircraftTypeId");

                    b.ToTable("Aircraft");
                });

            modelBuilder.Entity("Logbook.DataLayer.AircraftType", b =>
                {
                    b.Property<int>("AircraftTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EngineCount")
                        .HasColumnType("int");

                    b.Property<string>("EngineType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WTC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WTG")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AircraftTypeId");

                    b.ToTable("AircraftType");
                });

            modelBuilder.Entity("Logbook.DataLayer.Flights", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AircraftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LandingTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TakeoffTime")
                        .HasColumnType("datetime2");

                    b.HasKey("FlightId");

                    b.HasIndex("AircraftId");

                    b.ToTable("Flight");
                });

            modelBuilder.Entity("Logbook.DataLayer.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FlightsFlightId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PIN")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlightsFlightId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Logbook.DataLayer.Aircraft", b =>
                {
                    b.HasOne("Logbook.DataLayer.AircraftType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeAircraftTypeId");
                });

            modelBuilder.Entity("Logbook.DataLayer.Flights", b =>
                {
                    b.HasOne("Logbook.DataLayer.Aircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId");
                });

            modelBuilder.Entity("Logbook.DataLayer.User", b =>
                {
                    b.HasOne("Logbook.DataLayer.Flights", null)
                        .WithMany("Pilots")
                        .HasForeignKey("FlightsFlightId");
                });
#pragma warning restore 612, 618
        }
    }
}
